name: Run test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
          cache: false # optional, default is true

      - name: Launch Tests
        run: go test -v .
